[2024-06-13T08:00:47.754+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T08:00:47.772+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T08:00:47.777+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T08:00:47.777+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-13T08:00:47.786+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_and_publish_race> on 2024-06-12 00:00:00+00:00
[2024-06-13T08:00:47.791+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=752) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T08:00:47.792+0000] {standard_task_runner.py:63} INFO - Started process 760 to run task
[2024-06-13T08:00:47.793+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow_with_kafka', 'fetch_and_publish_race', 'scheduled__2024-06-12T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_scrape.py', '--cfg-path', '/tmp/tmpq6zry0dc']
[2024-06-13T08:00:47.794+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask fetch_and_publish_race
[2024-06-13T08:00:47.828+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [running]> on host 2af4b76eb3c8
[2024-06-13T08:00:47.885+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow_with_kafka' AIRFLOW_CTX_TASK_ID='fetch_and_publish_race' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-12T00:00:00+00:00'
[2024-06-13T08:00:47.885+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T08:00:52.337+0000] {logging_mixin.py:188} INFO - tried to find producer
[2024-06-13T08:00:52.338+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.31.0.6', 9092)]>: connecting to kafka:9092 [('172.31.0.6', 9092) IPv4]
[2024-06-13T08:00:52.339+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-06-13T08:00:52.339+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.31.0.6', 9092)]>: Connection complete.
[2024-06-13T08:00:52.442+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-06-13T08:00:52.442+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-06-13T08:00:52.596+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.31.0.6', 9092)]>: connecting to kafka:9092 [('172.31.0.6', 9092) IPv4]
[2024-06-13T08:00:52.597+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.31.0.6', 9092)]>: Connection complete.
[2024-06-13T08:00:52.597+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.31.0.6', 9092)]>: Closing connection. 
[2024-06-13T08:00:52.711+0000] {kafka.py:486} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2024-06-13T08:00:52.720+0000] {conn.py:673} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connected> [IPv4 ('172.31.0.6', 9092)]>: Closing connection. 
[2024-06-13T08:00:52.721+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-13T08:00:52.721+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T08:00:52.728+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow_with_kafka, task_id=fetch_and_publish_race, run_id=scheduled__2024-06-12T00:00:00+00:00, execution_date=20240612T000000, start_date=20240613T080047, end_date=20240613T080052
[2024-06-13T08:00:52.779+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T08:00:52.796+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-13T08:00:52.798+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-13T08:44:12.342+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T08:44:12.357+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T08:44:12.363+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T08:44:12.363+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-13T08:44:12.371+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_and_publish_race> on 2024-06-12 00:00:00+00:00
[2024-06-13T08:44:12.376+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=92) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T08:44:12.378+0000] {standard_task_runner.py:63} INFO - Started process 101 to run task
[2024-06-13T08:44:12.378+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow_with_kafka', 'fetch_and_publish_race', 'scheduled__2024-06-12T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_scrape.py', '--cfg-path', '/tmp/tmpvpcmv6in']
[2024-06-13T08:44:12.381+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask fetch_and_publish_race
[2024-06-13T08:44:12.424+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [running]> on host c97498906c69
[2024-06-13T08:44:12.493+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow_with_kafka' AIRFLOW_CTX_TASK_ID='fetch_and_publish_race' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-12T00:00:00+00:00'
[2024-06-13T08:44:12.494+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T08:44:15.220+0000] {logging_mixin.py:188} INFO - tried to find producer
[2024-06-13T08:44:15.222+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('192.168.0.6', 9092)]>: connecting to kafka:9092 [('192.168.0.6', 9092) IPv4]
[2024-06-13T08:44:15.223+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-06-13T08:44:15.224+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('192.168.0.6', 9092)]>: Connection complete.
[2024-06-13T08:44:15.326+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-06-13T08:44:15.327+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-06-13T08:44:15.481+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('192.168.0.6', 9092)]>: connecting to kafka:9092 [('192.168.0.6', 9092) IPv4]
[2024-06-13T08:44:15.482+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('192.168.0.6', 9092)]>: Connection complete.
[2024-06-13T08:44:15.482+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('192.168.0.6', 9092)]>: Closing connection. 
[2024-06-13T08:44:15.596+0000] {kafka.py:486} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2024-06-13T08:44:15.604+0000] {conn.py:673} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connected> [IPv4 ('192.168.0.6', 9092)]>: Closing connection. 
[2024-06-13T08:44:15.605+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-13T08:44:15.605+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T08:44:15.614+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow_with_kafka, task_id=fetch_and_publish_race, run_id=scheduled__2024-06-12T00:00:00+00:00, execution_date=20240612T000000, start_date=20240613T084412, end_date=20240613T084415
[2024-06-13T08:44:15.643+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T08:44:15.660+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-13T08:44:15.661+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-13T09:21:00.134+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T09:21:00.149+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T09:21:00.153+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T09:21:00.154+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-13T09:21:00.162+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_and_publish_race> on 2024-06-12 00:00:00+00:00
[2024-06-13T09:21:00.167+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=589) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T09:21:00.169+0000] {standard_task_runner.py:63} INFO - Started process 597 to run task
[2024-06-13T09:21:00.169+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow_with_kafka', 'fetch_and_publish_race', 'scheduled__2024-06-12T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_scrape.py', '--cfg-path', '/tmp/tmpxvn5i9y7']
[2024-06-13T09:21:00.171+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask fetch_and_publish_race
[2024-06-13T09:21:00.207+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [running]> on host a1ac73387874
[2024-06-13T09:21:00.267+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow_with_kafka' AIRFLOW_CTX_TASK_ID='fetch_and_publish_race' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-12T00:00:00+00:00'
[2024-06-13T09:21:00.269+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T09:21:02.003+0000] {logging_mixin.py:188} INFO - tried to find producer
[2024-06-13T09:21:02.006+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('192.168.32.6', 9092)]>: connecting to kafka:9092 [('192.168.32.6', 9092) IPv4]
[2024-06-13T09:21:02.007+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-06-13T09:21:02.008+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('192.168.32.6', 9092)]>: Connection complete.
[2024-06-13T09:21:02.113+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-06-13T09:21:02.113+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-06-13T09:21:02.268+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('192.168.32.6', 9092)]>: connecting to kafka:9092 [('192.168.32.6', 9092) IPv4]
[2024-06-13T09:21:02.268+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('192.168.32.6', 9092)]>: Connection complete.
[2024-06-13T09:21:02.269+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('192.168.32.6', 9092)]>: Closing connection. 
[2024-06-13T09:21:02.385+0000] {kafka.py:486} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2024-06-13T09:21:02.392+0000] {conn.py:673} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connected> [IPv4 ('192.168.32.6', 9092)]>: Closing connection. 
[2024-06-13T09:21:02.393+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-13T09:21:02.393+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T09:21:02.401+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow_with_kafka, task_id=fetch_and_publish_race, run_id=scheduled__2024-06-12T00:00:00+00:00, execution_date=20240612T000000, start_date=20240613T092100, end_date=20240613T092102
[2024-06-13T09:21:02.430+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T09:21:02.447+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-13T09:21:02.449+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-13T09:45:27.178+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T09:45:27.193+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T09:45:27.198+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T09:45:27.198+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-13T09:45:27.209+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_and_publish_race> on 2024-06-12 00:00:00+00:00
[2024-06-13T09:45:27.214+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=636) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T09:45:27.216+0000] {standard_task_runner.py:63} INFO - Started process 647 to run task
[2024-06-13T09:45:27.215+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow_with_kafka', 'fetch_and_publish_race', 'scheduled__2024-06-12T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_scrape.py', '--cfg-path', '/tmp/tmp0xwj5iyq']
[2024-06-13T09:45:27.217+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask fetch_and_publish_race
[2024-06-13T09:45:27.256+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [running]> on host 765a3094118c
[2024-06-13T09:45:27.316+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow_with_kafka' AIRFLOW_CTX_TASK_ID='fetch_and_publish_race' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-12T00:00:00+00:00'
[2024-06-13T09:45:27.317+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T09:45:29.434+0000] {logging_mixin.py:188} INFO - tried to find producer
[2024-06-13T09:45:29.436+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('192.168.48.6', 9092)]>: connecting to kafka:9092 [('192.168.48.6', 9092) IPv4]
[2024-06-13T09:45:29.437+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-06-13T09:45:29.437+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('192.168.48.6', 9092)]>: Connection complete.
[2024-06-13T09:45:29.541+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-06-13T09:45:29.542+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-06-13T09:45:29.696+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('192.168.48.6', 9092)]>: connecting to kafka:9092 [('192.168.48.6', 9092) IPv4]
[2024-06-13T09:45:29.697+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('192.168.48.6', 9092)]>: Connection complete.
[2024-06-13T09:45:29.697+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('192.168.48.6', 9092)]>: Closing connection. 
[2024-06-13T09:45:29.816+0000] {kafka.py:486} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2024-06-13T09:45:29.825+0000] {conn.py:673} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connected> [IPv4 ('192.168.48.6', 9092)]>: Closing connection. 
[2024-06-13T09:45:29.826+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-13T09:45:29.827+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T09:45:29.835+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow_with_kafka, task_id=fetch_and_publish_race, run_id=scheduled__2024-06-12T00:00:00+00:00, execution_date=20240612T000000, start_date=20240613T094527, end_date=20240613T094529
[2024-06-13T09:45:29.879+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T09:45:29.895+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-13T09:45:29.897+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-13T09:56:26.170+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T09:56:26.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T09:56:26.204+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T09:56:26.205+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-13T09:56:26.219+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_and_publish_race> on 2024-06-12 00:00:00+00:00
[2024-06-13T09:56:26.227+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=587) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T09:56:26.229+0000] {standard_task_runner.py:63} INFO - Started process 597 to run task
[2024-06-13T09:56:26.230+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow_with_kafka', 'fetch_and_publish_race', 'scheduled__2024-06-12T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_scrape.py', '--cfg-path', '/tmp/tmpnqp5cqlm']
[2024-06-13T09:56:26.233+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask fetch_and_publish_race
[2024-06-13T09:56:26.292+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [running]> on host 611decc8aca0
[2024-06-13T09:56:26.369+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow_with_kafka' AIRFLOW_CTX_TASK_ID='fetch_and_publish_race' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-12T00:00:00+00:00'
[2024-06-13T09:56:26.370+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T09:56:28.591+0000] {logging_mixin.py:188} INFO - tried to find producer
[2024-06-13T09:56:28.594+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('192.168.64.6', 9092)]>: connecting to kafka:9092 [('192.168.64.6', 9092) IPv4]
[2024-06-13T09:56:28.595+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-06-13T09:56:28.595+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('192.168.64.6', 9092)]>: Connection complete.
[2024-06-13T09:56:28.698+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-06-13T09:56:28.698+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-06-13T09:56:28.853+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('192.168.64.6', 9092)]>: connecting to kafka:9092 [('192.168.64.6', 9092) IPv4]
[2024-06-13T09:56:28.853+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('192.168.64.6', 9092)]>: Connection complete.
[2024-06-13T09:56:28.853+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('192.168.64.6', 9092)]>: Closing connection. 
[2024-06-13T09:56:29.071+0000] {kafka.py:486} INFO - Closing the Kafka producer with 9223372036.0 secs timeout.
[2024-06-13T09:56:29.105+0000] {conn.py:673} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connected> [IPv4 ('192.168.64.6', 9092)]>: Closing connection. 
[2024-06-13T09:56:29.106+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-13T09:56:29.106+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T09:56:29.115+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow_with_kafka, task_id=fetch_and_publish_race, run_id=scheduled__2024-06-12T00:00:00+00:00, execution_date=20240612T000000, start_date=20240613T095626, end_date=20240613T095629
[2024-06-13T09:56:29.133+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T09:56:29.152+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-13T09:56:29.153+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-13T12:23:25.516+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T12:23:25.534+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T12:23:25.539+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T12:23:25.540+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-13T12:23:25.548+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_and_publish_race> on 2024-06-12 00:00:00+00:00
[2024-06-13T12:23:25.552+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=585) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T12:23:25.553+0000] {standard_task_runner.py:63} INFO - Started process 593 to run task
[2024-06-13T12:23:25.554+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow_with_kafka', 'fetch_and_publish_race', 'scheduled__2024-06-12T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_scrape.py', '--cfg-path', '/tmp/tmpoqir9efj']
[2024-06-13T12:23:25.555+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask fetch_and_publish_race
[2024-06-13T12:23:25.590+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [running]> on host 5dd2cf9078a8
[2024-06-13T12:23:25.654+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow_with_kafka' AIRFLOW_CTX_TASK_ID='fetch_and_publish_race' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-12T00:00:00+00:00'
[2024-06-13T12:23:25.655+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T12:24:25.805+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T12:24:25.805+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_data_scrape.py", line 136, in fetch_and_publish_race
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-06-13T12:24:25.817+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=f1_data_pipeline_taskflow_with_kafka, task_id=fetch_and_publish_race, run_id=scheduled__2024-06-12T00:00:00+00:00, execution_date=20240612T000000, start_date=20240613T122325, end_date=20240613T122425
[2024-06-13T12:24:25.827+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 36 for task fetch_and_publish_race (Expecting value: line 1 column 1 (char 0); 593)
[2024-06-13T12:24:25.834+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T12:24:25.850+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T12:24:25.853+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-13T14:20:59.842+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T14:20:59.864+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T14:20:59.870+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T14:20:59.870+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-13T14:20:59.880+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): fetch_and_publish_race> on 2024-06-12 00:00:00+00:00
[2024-06-13T14:20:59.886+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=593) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T14:20:59.887+0000] {standard_task_runner.py:63} INFO - Started process 599 to run task
[2024-06-13T14:20:59.888+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow_with_kafka', 'fetch_and_publish_race', 'scheduled__2024-06-12T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_scrape.py', '--cfg-path', '/tmp/tmp4v2_qi1s']
[2024-06-13T14:20:59.890+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask fetch_and_publish_race
[2024-06-13T14:20:59.926+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_race scheduled__2024-06-12T00:00:00+00:00 [running]> on host 9503b7b620e4
[2024-06-13T14:20:59.985+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow_with_kafka' AIRFLOW_CTX_TASK_ID='fetch_and_publish_race' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-12T00:00:00+00:00'
[2024-06-13T14:20:59.986+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T14:22:00.252+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T14:22:00.252+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_data_scrape.py", line 136, in fetch_and_publish_race
    data = response.json()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-06-13T14:22:00.267+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=f1_data_pipeline_taskflow_with_kafka, task_id=fetch_and_publish_race, run_id=scheduled__2024-06-12T00:00:00+00:00, execution_date=20240612T000000, start_date=20240613T142059, end_date=20240613T142200
[2024-06-13T14:22:00.279+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 36 for task fetch_and_publish_race (Expecting value: line 1 column 1 (char 0); 599)
[2024-06-13T14:22:00.301+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T14:22:00.308+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
