[2024-06-03T09:34:46.271+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T09:34:46.288+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__11 manual__2024-06-03T09:33:56.254036+00:00 [queued]>
[2024-06-03T09:34:46.294+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__11 manual__2024-06-03T09:33:56.254036+00:00 [queued]>
[2024-06-03T09:34:46.294+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-03T09:34:46.303+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__11> on 2024-06-03 09:33:56.254036+00:00
[2024-06-03T09:34:46.309+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=530) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-03T09:34:46.310+0000] {standard_task_runner.py:63} INFO - Started process 537 to run task
[2024-06-03T09:34:46.310+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__11', 'manual__2024-06-03T09:33:56.254036+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp74gpglkz']
[2024-06-03T09:34:46.312+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask load_data__11
[2024-06-03T09:34:46.344+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__11 manual__2024-06-03T09:33:56.254036+00:00 [running]> on host acc449a1db53
[2024-06-03T09:34:46.517+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__11' AIRFLOW_CTX_EXECUTION_DATE='2024-06-03T09:33:56.254036+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-03T09:33:56.254036+00:00'
[2024-06-03T09:34:46.518+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T09:34:46.519+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-03T09:34:46.519+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-06-03T09:34:46.529+0000] {warnings.py:110} WARNING - /opt/***/dags/etl_dag.py:197: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df.to_sql(table_name, engine, if_exists='append', index=False)

[2024-06-03T09:34:50.499+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-03T09:34:50.499+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T09:34:50.506+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow, task_id=load_data__11, run_id=manual__2024-06-03T09:33:56.254036+00:00, execution_date=20240603T093356, start_date=20240603T093446, end_date=20240603T093450
[2024-06-03T09:34:50.540+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-03T09:34:50.554+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T09:34:50.555+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
